{{- if eq (get (default dict .Values.podAnnotations) "inject.xfsc.io/enabled") "true" }}
{{- $secretName := printf "%s-postgres-credentials" .Release.Name -}}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- $password := "" -}}

{{- if $existing }}
{{- $password = index $existing.data "password" | b64dec -}}
{{- else }}
{{- $password = randAlphaNum 32 -}}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: {{ .Release.Name }}
  password: {{ $password }}
{{- end }}