version: '2.2'
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PARAMS=sslmode=disable
  nats:
    image: nats:2.10.10
    ports:
      - 4222:4222
      - 8222:8222