name: Go QA

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  actions: write
  
jobs:
  call-go-qa:
    secrets: inherit
    uses: eclipse-xfsc/dev-ops/.github/workflows/go-qa.yml@main
